/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDBMLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(at.jku.se.dbml.dBML.DBMLPackage.eINSTANCE);
		return result;
	}
}
