/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDBMLScopeProvider extends DelegatingScopeProvider {
}
