/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DBMLStandaloneSetup extends DBMLStandaloneSetupGenerated {

	public static void doSetup() {
		new DBMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
