/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DBMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/jku/se/dbml/parser/antlr/internal/InternalDBML.tokens");
	}
}
