/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.parser.antlr;

import at.jku.se.dbml.parser.antlr.internal.InternalDBMLParser;
import at.jku.se.dbml.services.DBMLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DBMLParser extends AbstractAntlrParser {

	@Inject
	private DBMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDBMLParser createParser(XtextTokenStream stream) {
		return new InternalDBMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DBMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DBMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
