/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.ide;

import at.jku.se.dbml.DBMLRuntimeModule;
import at.jku.se.dbml.DBMLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DBMLIdeSetup extends DBMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DBMLRuntimeModule(), new DBMLIdeModule()));
	}
	
}
