/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.ui;

import at.jku.se.dbml.ui.internal.DbmlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DBMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DbmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DbmlActivator activator = DbmlActivator.getInstance();
		return activator != null ? activator.getInjector(DbmlActivator.AT_JKU_SE_DBML_DBML) : null;
	}

}
