/**
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.dBML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.se.dbml.dBML.NestedRef#getTable <em>Table</em>}</li>
 *   <li>{@link at.jku.se.dbml.dBML.NestedRef#getAttr <em>Attr</em>}</li>
 * </ul>
 *
 * @see at.jku.se.dbml.dBML.DBMLPackage#getNestedRef()
 * @model
 * @generated
 */
public interface NestedRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(Table)
   * @see at.jku.se.dbml.dBML.DBMLPackage#getNestedRef_Table()
   * @model
   * @generated
   */
  Table getTable();

  /**
   * Sets the value of the '{@link at.jku.se.dbml.dBML.NestedRef#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(Table value);

  /**
   * Returns the value of the '<em><b>Attr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr</em>' attribute.
   * @see #setAttr(String)
   * @see at.jku.se.dbml.dBML.DBMLPackage#getNestedRef_Attr()
   * @model
   * @generated
   */
  String getAttr();

  /**
   * Sets the value of the '{@link at.jku.se.dbml.dBML.NestedRef#getAttr <em>Attr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attr</em>' attribute.
   * @see #getAttr()
   * @generated
   */
  void setAttr(String value);

} // NestedRef
