/**
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.dBML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.jku.se.dbml.dBML.Ref#getLeft <em>Left</em>}</li>
 *   <li>{@link at.jku.se.dbml.dBML.Ref#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see at.jku.se.dbml.dBML.DBMLPackage#getRef()
 * @model
 * @generated
 */
public interface Ref extends Statement
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(NestedRef)
   * @see at.jku.se.dbml.dBML.DBMLPackage#getRef_Left()
   * @model containment="true"
   * @generated
   */
  NestedRef getLeft();

  /**
   * Sets the value of the '{@link at.jku.se.dbml.dBML.Ref#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(NestedRef value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(NestedRef)
   * @see at.jku.se.dbml.dBML.DBMLPackage#getRef_Right()
   * @model containment="true"
   * @generated
   */
  NestedRef getRight();

  /**
   * Sets the value of the '{@link at.jku.se.dbml.dBML.Ref#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(NestedRef value);

} // Ref
