/**
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.dBML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.jku.se.dbml.dBML.DBMLPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
