/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.ui.tests;

import at.jku.se.dbml.ui.internal.DbmlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DBMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DbmlActivator.getInstance().getInjector("at.jku.se.dbml.DBML");
	}

}
