/*
 * generated by Xtext 2.26.0
 */
package at.jku.se.dbml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DBMLUiModule extends AbstractDBMLUiModule {

	public DBMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
